/*
 * The MIT License
 *
 * Copyright 2024 pnot0.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.argotech.aplicacao.telas;

import br.com.argotech.aplicacao.model.Estoque;



/**
 * @author DiogoNucci
 * @version 1.0
 */
public class TelaEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEstoque
     */
    
    Estoque estoque = new Estoque();
    
    public TelaEstoque() {
        initComponents();
        estoque.atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idEstoqueLabel = new javax.swing.JLabel();
        buscarEstoqueButton = new javax.swing.JButton();
        idEstoqueNumberLabel = new javax.swing.JLabel();
        obrigatorioEstoqueLabel = new javax.swing.JLabel();
        criarEstoqueButton = new javax.swing.JButton();
        nomeEstoqueTextField = new javax.swing.JTextField();
        alterarEstoqueButton = new javax.swing.JButton();
        deletarEstoqueButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        nomeEstoqueLabel = new javax.swing.JLabel();
        quantidadeEstoqueLabel = new javax.swing.JLabel();
        buscaEstoqueTextField = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        estoqueEstoqueTable = new javax.swing.JTable();
        categoriaEstoqueComboBox = new javax.swing.JComboBox<>();
        quantidadeEstoqueSpinner = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Estoque");
        setPreferredSize(new java.awt.Dimension(620, 470));

        idEstoqueLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        idEstoqueLabel.setText("ID:");

        buscarEstoqueButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarEstoqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEstoqueButtonActionPerformed(evt);
            }
        });

        idEstoqueNumberLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        idEstoqueNumberLabel.setText("ID");

        obrigatorioEstoqueLabel.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        obrigatorioEstoqueLabel.setText("Campos obrigatórios: *");

        criarEstoqueButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        criarEstoqueButton.setText("Adicionar Estoque");
        criarEstoqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarEstoqueButtonActionPerformed(evt);
            }
        });

        nomeEstoqueTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        alterarEstoqueButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        alterarEstoqueButton.setText("Alterar Estoque");
        alterarEstoqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEstoqueButtonActionPerformed(evt);
            }
        });

        deletarEstoqueButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deletarEstoqueButton.setText("Deletar Estoque");
        deletarEstoqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarEstoqueButtonActionPerformed(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        nomeEstoqueLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        nomeEstoqueLabel.setText("Nome estoque*");

        quantidadeEstoqueLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        quantidadeEstoqueLabel.setText("Quantidade*");

        buscaEstoqueTextField.setToolTipText("");
        buscaEstoqueTextField.setName(""); // NOI18N
        buscaEstoqueTextField.setVerifyInputWhenFocusTarget(false);

        estoqueEstoqueTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        estoqueEstoqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Categoria", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        estoqueEstoqueTable.setFocusable(false);
        estoqueEstoqueTable.getTableHeader().setReorderingAllowed(false);
        estoqueEstoqueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estoqueEstoqueTableMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(estoqueEstoqueTable);

        categoriaEstoqueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU/Processador", "Cooler CPU", "Placa mãe", "Memoria RAM", "Placa de vídeo", "Armazenamento", "Fonte", "Cabo", "Cooler Gabinete", "Gabinete", "Outro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limparButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(criarEstoqueButton)
                        .addGap(14, 14, 14)
                        .addComponent(alterarEstoqueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletarEstoqueButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscaEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarEstoqueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(obrigatorioEstoqueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeEstoqueLabel)
                                    .addComponent(quantidadeEstoqueLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantidadeEstoqueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idEstoqueLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idEstoqueNumberLabel))
                                    .addComponent(categoriaEstoqueComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(obrigatorioEstoqueLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarEstoqueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscaEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEstoqueLabel)
                    .addComponent(nomeEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEstoqueLabel)
                    .addComponent(idEstoqueNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeEstoqueLabel)
                    .addComponent(categoriaEstoqueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeEstoqueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarEstoqueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarEstoqueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletarEstoqueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarEstoqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEstoqueButtonActionPerformed
        estoque.atualizar();
    }//GEN-LAST:event_buscarEstoqueButtonActionPerformed

    private void criarEstoqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarEstoqueButtonActionPerformed
        estoque.criar();
    }//GEN-LAST:event_criarEstoqueButtonActionPerformed

    private void alterarEstoqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEstoqueButtonActionPerformed
        estoque.alterar();
    }//GEN-LAST:event_alterarEstoqueButtonActionPerformed

    private void deletarEstoqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarEstoqueButtonActionPerformed
        estoque.deletar();
    }//GEN-LAST:event_deletarEstoqueButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        estoque.limparCampos();
    }//GEN-LAST:event_limparButtonActionPerformed

    private void estoqueEstoqueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueEstoqueTableMouseClicked
        estoque.setarCampos();
    }//GEN-LAST:event_estoqueEstoqueTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton alterarEstoqueButton;
    public static javax.swing.JTextField buscaEstoqueTextField;
    private javax.swing.JButton buscarEstoqueButton;
    public static javax.swing.JComboBox<String> categoriaEstoqueComboBox;
    private javax.swing.JButton criarEstoqueButton;
    private javax.swing.JButton deletarEstoqueButton;
    public static javax.swing.JTable estoqueEstoqueTable;
    private javax.swing.JLabel idEstoqueLabel;
    public static javax.swing.JLabel idEstoqueNumberLabel;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeEstoqueLabel;
    public static javax.swing.JTextField nomeEstoqueTextField;
    private javax.swing.JLabel obrigatorioEstoqueLabel;
    private javax.swing.JLabel quantidadeEstoqueLabel;
    public static javax.swing.JSpinner quantidadeEstoqueSpinner;
    // End of variables declaration//GEN-END:variables
}
