/*
 * The MIT License
 *
 * Copyright 2024 pnot0.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.argotech.aplicacao.telas;

import br.com.argotech.aplicacao.model.Venda;

/**
 * @author DiogoNucci
 * @version 1.0
 */
public class TelaVenda extends javax.swing.JInternalFrame{

    /**
     * Creates new form TelaVenda
     */
   
    Venda venda = new Venda();
    
    public TelaVenda() {
        initComponents();
        venda.atualizar();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendaScrollPane = new javax.swing.JScrollPane();
        vendaVendaTable = new javax.swing.JTable();
        buscarVendaVendaButton = new javax.swing.JButton();
        buscaVendaVendaTextField = new javax.swing.JTextField();
        computadoresVendaPanel = new javax.swing.JPanel();
        computadorScrollPane = new javax.swing.JScrollPane();
        computadorVendaTable = new javax.swing.JTable();
        buscaComputadorVendaTextField = new javax.swing.JTextField();
        buscarComputadorVendaButton = new javax.swing.JButton();
        idComputadorVendaLabel = new javax.swing.JLabel();
        idComputadorVendaNumberTextField = new javax.swing.JTextField();
        limparIDComputadorVendaButton = new javax.swing.JButton();
        clientesVendaPanel = new javax.swing.JPanel();
        clienteScrollPane = new javax.swing.JScrollPane();
        clienteVendaTable = new javax.swing.JTable();
        buscaClienteVendaTextField = new javax.swing.JTextField();
        buscarClienteVendaButton = new javax.swing.JButton();
        idClienteVendaLabel = new javax.swing.JLabel();
        idClienteVendaNumberTextField = new javax.swing.JTextField();
        limparIDClienteVendaButton = new javax.swing.JButton();
        idVendaLabel = new javax.swing.JLabel();
        idVendaNumberLabel = new javax.swing.JLabel();
        quantidadeVendaSpinner = new javax.swing.JSpinner();
        precoVendaFormattedTextField = new javax.swing.JFormattedTextField();
        quantidadeVendaLabel = new javax.swing.JLabel();
        valorVendaLabel = new javax.swing.JLabel();
        alterarVendaButton = new javax.swing.JButton();
        adicionarVendaButton = new javax.swing.JButton();
        deletarVendaButton = new javax.swing.JButton();
        limparVendaButton = new javax.swing.JButton();
        pesquisarVendaLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vendas");

        vendaVendaTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        vendaVendaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDVenda", "IDCliente", "IDPC", "Quantidade", "Preço", "Total", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vendaVendaTable.setFocusable(false);
        vendaVendaTable.getTableHeader().setReorderingAllowed(false);
        vendaVendaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendaVendaTableMouseClicked(evt);
            }
        });
        vendaScrollPane.setViewportView(vendaVendaTable);

        buscarVendaVendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarVendaVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVendaVendaButtonActionPerformed(evt);
            }
        });

        computadoresVendaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Computadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter Medium", 0, 18))); // NOI18N

        computadorVendaTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        computadorVendaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        computadorVendaTable.setFocusable(false);
        computadorVendaTable.getTableHeader().setReorderingAllowed(false);
        computadorVendaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computadorVendaTableMouseClicked(evt);
            }
        });
        computadorScrollPane.setViewportView(computadorVendaTable);

        buscarComputadorVendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarComputadorVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarComputadorVendaButtonActionPerformed(evt);
            }
        });

        idComputadorVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        idComputadorVendaLabel.setText("ID Computador:");

        idComputadorVendaNumberTextField.setFont(new java.awt.Font("Inter Medium", 1, 18)); // NOI18N
        idComputadorVendaNumberTextField.setEnabled(false);

        limparIDComputadorVendaButton.setText("Limpar ID");
        limparIDComputadorVendaButton.setEnabled(false);
        limparIDComputadorVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparIDComputadorVendaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout computadoresVendaPanelLayout = new javax.swing.GroupLayout(computadoresVendaPanel);
        computadoresVendaPanel.setLayout(computadoresVendaPanelLayout);
        computadoresVendaPanelLayout.setHorizontalGroup(
            computadoresVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadoresVendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(computadoresVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computadoresVendaPanelLayout.createSequentialGroup()
                        .addComponent(buscaComputadorVendaTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarComputadorVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(computadoresVendaPanelLayout.createSequentialGroup()
                        .addComponent(computadorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(computadoresVendaPanelLayout.createSequentialGroup()
                        .addComponent(idComputadorVendaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idComputadorVendaNumberTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparIDComputadorVendaButton)
                        .addContainerGap())))
        );
        computadoresVendaPanelLayout.setVerticalGroup(
            computadoresVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadoresVendaPanelLayout.createSequentialGroup()
                .addGroup(computadoresVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscaComputadorVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarComputadorVendaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(computadoresVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idComputadorVendaLabel)
                    .addComponent(idComputadorVendaNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparIDComputadorVendaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computadorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        clientesVendaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter Medium", 0, 18))); // NOI18N

        clienteVendaTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        clienteVendaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Fone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clienteVendaTable.setFocusable(false);
        clienteVendaTable.getTableHeader().setReorderingAllowed(false);
        clienteVendaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteVendaTableMouseClicked(evt);
            }
        });
        clienteScrollPane.setViewportView(clienteVendaTable);

        buscarClienteVendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarClienteVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteVendaButtonActionPerformed(evt);
            }
        });

        idClienteVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        idClienteVendaLabel.setText("ID Cliente:");

        idClienteVendaNumberTextField.setFont(new java.awt.Font("Inter Medium", 1, 18)); // NOI18N
        idClienteVendaNumberTextField.setEnabled(false);

        limparIDClienteVendaButton.setText("Limpar ID");
        limparIDClienteVendaButton.setEnabled(false);
        limparIDClienteVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparIDClienteVendaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientesVendaPanelLayout = new javax.swing.GroupLayout(clientesVendaPanel);
        clientesVendaPanel.setLayout(clientesVendaPanelLayout);
        clientesVendaPanelLayout.setHorizontalGroup(
            clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesVendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesVendaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clientesVendaPanelLayout.createSequentialGroup()
                                .addComponent(buscaClienteVendaTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarClienteVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(clienteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(clientesVendaPanelLayout.createSequentialGroup()
                        .addComponent(idClienteVendaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idClienteVendaNumberTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparIDClienteVendaButton)
                        .addContainerGap())))
        );
        clientesVendaPanelLayout.setVerticalGroup(
            clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesVendaPanelLayout.createSequentialGroup()
                .addGroup(clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscaClienteVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarClienteVendaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idClienteVendaLabel)
                        .addComponent(idClienteVendaNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(limparIDClienteVendaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        idVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        idVendaLabel.setText("ID Venda:");

        idVendaNumberLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        idVendaNumberLabel.setText("ID");

        quantidadeVendaSpinner.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N

        precoVendaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00" , java.text.DecimalFormatSymbols.getInstance(java.util.Locale.US)))));

        quantidadeVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        quantidadeVendaLabel.setText("Quantidade");

        valorVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        valorVendaLabel.setText("Valor (R$)");

        alterarVendaButton.setText("Alterar Venda");
        alterarVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarVendaButtonActionPerformed(evt);
            }
        });

        adicionarVendaButton.setText("Adicionar Venda");
        adicionarVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarVendaButtonActionPerformed(evt);
            }
        });

        deletarVendaButton.setText("Deletar Venda");
        deletarVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarVendaButtonActionPerformed(evt);
            }
        });

        limparVendaButton.setText("Limpar");
        limparVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparVendaButtonActionPerformed(evt);
            }
        });

        pesquisarVendaLabel.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        pesquisarVendaLabel.setText("Pesquisar IDVenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(computadoresVendaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientesVendaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quantidadeVendaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantidadeVendaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valorVendaLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(precoVendaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deletarVendaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(alterarVendaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idVendaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idVendaNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adicionarVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pesquisarVendaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaVendaVendaTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarVendaVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 386, Short.MAX_VALUE)
                        .addComponent(limparVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarVendaVendaButton)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buscaVendaVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pesquisarVendaLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(computadoresVendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientesVendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idVendaLabel)
                                    .addComponent(idVendaNumberLabel))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(adicionarVendaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quantidadeVendaLabel)
                                .addComponent(quantidadeVendaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alterarVendaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valorVendaLabel)
                                .addComponent(precoVendaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deletarVendaButton))
                        .addGap(18, 18, 18)
                        .addComponent(limparVendaButton)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computadorVendaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computadorVendaTableMouseClicked
        venda.setarIDComputador();
        limparIDComputadorVendaButton.setEnabled(true);
    }//GEN-LAST:event_computadorVendaTableMouseClicked

    private void clienteVendaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteVendaTableMouseClicked
        venda.setarIDCliente();
        limparIDClienteVendaButton.setEnabled(true);
    }//GEN-LAST:event_clienteVendaTableMouseClicked

    private void vendaVendaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendaVendaTableMouseClicked
        venda.setarCampos();
        limparIDClienteVendaButton.setEnabled(true);
        limparIDComputadorVendaButton.setEnabled(true);
    }//GEN-LAST:event_vendaVendaTableMouseClicked

    private void buscarVendaVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVendaVendaButtonActionPerformed
        venda.atualizar();
    }//GEN-LAST:event_buscarVendaVendaButtonActionPerformed

    private void buscarComputadorVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarComputadorVendaButtonActionPerformed
        venda.atualizarComputador();
    }//GEN-LAST:event_buscarComputadorVendaButtonActionPerformed

    private void buscarClienteVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteVendaButtonActionPerformed
        venda.atualizarCliente();
    }//GEN-LAST:event_buscarClienteVendaButtonActionPerformed

    private void adicionarVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarVendaButtonActionPerformed
        venda.criar();
    }//GEN-LAST:event_adicionarVendaButtonActionPerformed

    private void alterarVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarVendaButtonActionPerformed
        venda.alterar();
    }//GEN-LAST:event_alterarVendaButtonActionPerformed

    private void deletarVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarVendaButtonActionPerformed
        venda.deletar();
    }//GEN-LAST:event_deletarVendaButtonActionPerformed

    private void limparIDComputadorVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparIDComputadorVendaButtonActionPerformed
        venda.limparIDComputador();
    }//GEN-LAST:event_limparIDComputadorVendaButtonActionPerformed

    private void limparIDClienteVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparIDClienteVendaButtonActionPerformed
        venda.limparIDCliente();
    }//GEN-LAST:event_limparIDClienteVendaButtonActionPerformed

    private void limparVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparVendaButtonActionPerformed
        venda.limparCampos();
    }//GEN-LAST:event_limparVendaButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarVendaButton;
    private javax.swing.JButton alterarVendaButton;
    public static javax.swing.JTextField buscaClienteVendaTextField;
    public static javax.swing.JTextField buscaComputadorVendaTextField;
    public static javax.swing.JTextField buscaVendaVendaTextField;
    private javax.swing.JButton buscarClienteVendaButton;
    private javax.swing.JButton buscarComputadorVendaButton;
    private javax.swing.JButton buscarVendaVendaButton;
    private javax.swing.JScrollPane clienteScrollPane;
    public static javax.swing.JTable clienteVendaTable;
    private javax.swing.JPanel clientesVendaPanel;
    private javax.swing.JScrollPane computadorScrollPane;
    public static javax.swing.JTable computadorVendaTable;
    private javax.swing.JPanel computadoresVendaPanel;
    private javax.swing.JButton deletarVendaButton;
    private javax.swing.JLabel idClienteVendaLabel;
    public static javax.swing.JTextField idClienteVendaNumberTextField;
    private javax.swing.JLabel idComputadorVendaLabel;
    public static javax.swing.JTextField idComputadorVendaNumberTextField;
    private javax.swing.JLabel idVendaLabel;
    public static javax.swing.JLabel idVendaNumberLabel;
    public static javax.swing.JButton limparIDClienteVendaButton;
    public static javax.swing.JButton limparIDComputadorVendaButton;
    private javax.swing.JButton limparVendaButton;
    private javax.swing.JLabel pesquisarVendaLabel;
    public static javax.swing.JFormattedTextField precoVendaFormattedTextField;
    private javax.swing.JLabel quantidadeVendaLabel;
    public static javax.swing.JSpinner quantidadeVendaSpinner;
    private javax.swing.JLabel valorVendaLabel;
    private javax.swing.JScrollPane vendaScrollPane;
    public static javax.swing.JTable vendaVendaTable;
    // End of variables declaration//GEN-END:variables
}
