/*
 * The MIT License
 *
 * Copyright 2024 pnot0.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.argotech.aplicacao.telas;

import br.com.argotech.aplicacao.model.Cliente;

/**
 * @author DiogoNucci
 * @version 1.0
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente
     */
    
    Cliente cliente = new Cliente();
    
    public TelaCliente() {
        initComponents();
        cliente.atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaClienteTextField = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        clienteClienteTable = new javax.swing.JTable();
        buscarClienteButton = new javax.swing.JButton();
        obrigatorioClienteLabel = new javax.swing.JLabel();
        nomeClienteTextField = new javax.swing.JTextField();
        enderecoClienteTextField = new javax.swing.JTextField();
        foneClienteTextField = new javax.swing.JTextField();
        emailClienteTextField = new javax.swing.JTextField();
        nomeClienteLabel = new javax.swing.JLabel();
        enderecoClienteLabel = new javax.swing.JLabel();
        foneClienteLabel = new javax.swing.JLabel();
        emailClienteLabel = new javax.swing.JLabel();
        idClienteClienteLabel = new javax.swing.JLabel();
        idClienteClienteNumberLabel = new javax.swing.JLabel();
        criarClienteButton = new javax.swing.JButton();
        alterarClienteButton = new javax.swing.JButton();
        deletarClienteButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        setPreferredSize(new java.awt.Dimension(620, 470));

        buscaClienteTextField.setToolTipText("");
        buscaClienteTextField.setName(""); // NOI18N
        buscaClienteTextField.setVerifyInputWhenFocusTarget(false);

        clienteClienteTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        clienteClienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "Fone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clienteClienteTable.setFocusable(false);
        clienteClienteTable.getTableHeader().setReorderingAllowed(false);
        clienteClienteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteClienteTableMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(clienteClienteTable);

        buscarClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteButtonActionPerformed(evt);
            }
        });

        obrigatorioClienteLabel.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        obrigatorioClienteLabel.setText("Campos obrigatórios: *");

        nomeClienteTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        enderecoClienteTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        foneClienteTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        emailClienteTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        nomeClienteLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        nomeClienteLabel.setText("Nome*");

        enderecoClienteLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        enderecoClienteLabel.setText("Endereço");

        foneClienteLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        foneClienteLabel.setText("Fone*");

        emailClienteLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        emailClienteLabel.setText("Email");

        idClienteClienteLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        idClienteClienteLabel.setText("ID:");

        idClienteClienteNumberLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        idClienteClienteNumberLabel.setText("ID");

        criarClienteButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        criarClienteButton.setText("Adicionar Cliente");
        criarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarClienteButtonActionPerformed(evt);
            }
        });

        alterarClienteButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        alterarClienteButton.setText("Alterar Cliente");
        alterarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteButtonActionPerformed(evt);
            }
        });

        deletarClienteButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deletarClienteButton.setText("Deletar Cliente");
        deletarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarClienteButtonActionPerformed(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foneClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(foneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeClienteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoClienteLabel)
                            .addComponent(emailClienteLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enderecoClienteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(emailClienteTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscaClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(obrigatorioClienteLabel)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idClienteClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idClienteClienteNumberLabel))
                            .addComponent(limparButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criarClienteButton)
                        .addGap(12, 12, 12)
                        .addComponent(alterarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletarClienteButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(obrigatorioClienteLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscaClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeClienteLabel)
                    .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailClienteLabel)
                    .addComponent(emailClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foneClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foneClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClienteClienteLabel)
                    .addComponent(idClienteClienteNumberLabel))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteClienteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteClienteTableMouseClicked
        cliente.setarCampos();
    }//GEN-LAST:event_clienteClienteTableMouseClicked

    private void buscarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteButtonActionPerformed
        cliente.atualizar();
    }//GEN-LAST:event_buscarClienteButtonActionPerformed

    private void criarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarClienteButtonActionPerformed
        cliente.criar();
    }//GEN-LAST:event_criarClienteButtonActionPerformed

    private void alterarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteButtonActionPerformed
        cliente.alterar();
    }//GEN-LAST:event_alterarClienteButtonActionPerformed

    private void deletarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarClienteButtonActionPerformed
        cliente.deletar();
    }//GEN-LAST:event_deletarClienteButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        cliente.limparCampos();
    }//GEN-LAST:event_limparButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton alterarClienteButton;
    public static javax.swing.JTextField buscaClienteTextField;
    private javax.swing.JButton buscarClienteButton;
    public static javax.swing.JTable clienteClienteTable;
    private javax.swing.JButton criarClienteButton;
    private javax.swing.JButton deletarClienteButton;
    private javax.swing.JLabel emailClienteLabel;
    public static javax.swing.JTextField emailClienteTextField;
    private javax.swing.JLabel enderecoClienteLabel;
    public static javax.swing.JTextField enderecoClienteTextField;
    private javax.swing.JLabel foneClienteLabel;
    public static javax.swing.JTextField foneClienteTextField;
    private javax.swing.JLabel idClienteClienteLabel;
    public static javax.swing.JLabel idClienteClienteNumberLabel;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeClienteLabel;
    public static javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JLabel obrigatorioClienteLabel;
    // End of variables declaration//GEN-END:variables
}
