/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.argotech.aplicacao.telas;

import br.com.argotech.aplicacao.dal.ModuloConector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author pnot0
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TelaUsuario() {
        initComponents();
    }
    
    private void criar(){
        String sql = "insert into tbusuarios(iduser,usuario,fone,login,senha,acesso) values(?,?,?,?,?,?)";
        try {
            con = ModuloConector.createConnection();
            pst = con.prepareStatement(sql);
            
            //Pega todos os parametros inseridos pelo usuario
            pst.setString(1, idTextField.getText());
            pst.setString(2, usuarioTextField.getText());
            pst.setString(3, foneTextField.getText());
            pst.setString(4, loginTextField.getText());
            pst.setString(5, senhaTextField.getText());
            pst.setString(6, perfilComboBox.getSelectedItem().toString());
            
            //Checa se campos obritarios foram preenchidos
            if(idTextField.getText().isEmpty() || usuarioTextField.getText().isEmpty() || loginTextField.getText().isEmpty() || senhaTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios");
            }
            
            int adicionar = pst.executeUpdate();
            //Checa se é póssivel adicionar o usuario e retorna a confirmação para o usuario
            if(adicionar>0){
                JOptionPane.showMessageDialog(null, "Usuario adicionado com sucesso");
                idTextField.setText(null);
                usuarioTextField.setText(null);
                foneTextField.setText(null);
                loginTextField.setText(null);
                senhaTextField.setText(null);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        usuarioTextField = new javax.swing.JTextField();
        foneTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        foneLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        perfilLabel = new javax.swing.JLabel();
        perfilComboBox = new javax.swing.JComboBox<>();
        criarUsuarioButton = new javax.swing.JButton();
        obrigatorioLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuario");

        idTextField.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        usuarioTextField.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        foneTextField.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        loginTextField.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        senhaTextField.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        idLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        idLabel.setText("ID*");

        usuarioLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        usuarioLabel.setText("Usuario*");

        foneLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        foneLabel.setText("Fone");

        loginLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        loginLabel.setText("Login*");

        senhaLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        senhaLabel.setText("Senha*");

        perfilLabel.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        perfilLabel.setText("Perfil");

        perfilComboBox.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        perfilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "usuario" }));

        criarUsuarioButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        criarUsuarioButton.setText("Criar Usuario");
        criarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarUsuarioButtonActionPerformed(evt);
            }
        });

        obrigatorioLabel.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        obrigatorioLabel.setText("Campos obrigatórios: *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foneLabel)
                            .addComponent(perfilLabel)
                            .addComponent(senhaLabel)
                            .addComponent(loginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuarioLabel)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idTextField)
                    .addComponent(usuarioTextField)
                    .addComponent(foneTextField)
                    .addComponent(loginTextField)
                    .addComponent(senhaTextField)
                    .addComponent(perfilComboBox, 0, 160, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criarUsuarioButton)
                    .addComponent(obrigatorioLabel))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(obrigatorioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioLabel)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foneLabel)
                    .addComponent(foneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaLabel)
                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilLabel)
                    .addComponent(criarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarUsuarioButtonActionPerformed
        criar();
    }//GEN-LAST:event_criarUsuarioButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarUsuarioButton;
    private javax.swing.JLabel foneLabel;
    private javax.swing.JTextField foneTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel obrigatorioLabel;
    private javax.swing.JComboBox<String> perfilComboBox;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
