/*
 * The MIT License
 *
 * Copyright 2024 pnot0.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.argotech.aplicacao.telas;

import br.com.argotech.aplicacao.model.Componente;
import br.com.argotech.aplicacao.model.Computador;

/**
 * @author DiogoNucci
 * @version 1.0
 */
public class TelaComputadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaComputadores
     */
    
    Computador computador = new Computador();
    Componente componente = new Componente();
    
    public TelaComputadores() {
        initComponents();
        computador.atualizar();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        computadorComputadorPanel = new javax.swing.JPanel();
        buscarComputadorButton = new javax.swing.JButton();
        computadorScrollPane = new javax.swing.JScrollPane();
        computadorComputadorTable = new javax.swing.JTable();
        idComputadorComputadorLabel = new javax.swing.JLabel();
        idComputadorComputadorNumberLabel = new javax.swing.JLabel();
        nomeComputadorLabel = new javax.swing.JLabel();
        nomeComputadorTextField = new javax.swing.JTextField();
        descComputadorLabel = new javax.swing.JLabel();
        descComputadorTextField = new javax.swing.JTextField();
        quantidadeComputadorLabel = new javax.swing.JLabel();
        quantidadeComputadorSpinner = new javax.swing.JSpinner();
        adicionarComputadorButton = new javax.swing.JButton();
        alterarComputadorButton = new javax.swing.JButton();
        deletarComputadorButton = new javax.swing.JButton();
        limparComputadorButton = new javax.swing.JButton();
        buscaComputadorTextField = new javax.swing.JTextField();
        componenteComputadorPanel = new javax.swing.JPanel();
        nomeComponenteTextField = new javax.swing.JTextField();
        idComponenteLabel = new javax.swing.JLabel();
        nomeComponenteLabel = new javax.swing.JLabel();
        quantidadeComponenteLabel = new javax.swing.JLabel();
        quantidadeComponenteSpinner = new javax.swing.JSpinner();
        categoriaComponenteLabel = new javax.swing.JLabel();
        categoriaComponenteComboBox = new javax.swing.JComboBox<>();
        adicionarComponenteButton = new javax.swing.JButton();
        alterarComponenteButton = new javax.swing.JButton();
        deletarComponenteButton = new javax.swing.JButton();
        idComponenteNumberLabel = new javax.swing.JLabel();
        componenteScrollPane = new javax.swing.JScrollPane();
        componenteComputadorTable = new javax.swing.JTable();
        limparComponenteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Computadores");

        computadorComputadorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Computadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter Medium", 0, 14))); // NOI18N

        buscarComputadorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        buscarComputadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarComputadorButtonActionPerformed(evt);
            }
        });

        computadorComputadorTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        computadorComputadorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDPC", "Nome", "Descrição", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        computadorComputadorTable.setFocusable(false);
        computadorComputadorTable.getTableHeader().setReorderingAllowed(false);
        computadorComputadorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computadorComputadorTableMouseClicked(evt);
            }
        });
        computadorScrollPane.setViewportView(computadorComputadorTable);

        idComputadorComputadorLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        idComputadorComputadorLabel.setText("ID Computador:");

        idComputadorComputadorNumberLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        idComputadorComputadorNumberLabel.setText("ID");

        nomeComputadorLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        nomeComputadorLabel.setText("Nome");

        nomeComputadorTextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N

        descComputadorLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        descComputadorLabel.setText("Descrição");

        descComputadorTextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N

        quantidadeComputadorLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        quantidadeComputadorLabel.setText("Quantidade");

        quantidadeComputadorSpinner.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N

        adicionarComputadorButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        adicionarComputadorButton.setText("Adicionar");
        adicionarComputadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarComputadorButtonActionPerformed(evt);
            }
        });

        alterarComputadorButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        alterarComputadorButton.setText("Alterar");
        alterarComputadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarComputadorButtonActionPerformed(evt);
            }
        });

        deletarComputadorButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        deletarComputadorButton.setText("Deletar");
        deletarComputadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarComputadorButtonActionPerformed(evt);
            }
        });

        limparComputadorButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        limparComputadorButton.setText("Limpar");
        limparComputadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparComputadorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout computadorComputadorPanelLayout = new javax.swing.GroupLayout(computadorComputadorPanel);
        computadorComputadorPanel.setLayout(computadorComputadorPanelLayout);
        computadorComputadorPanelLayout.setHorizontalGroup(
            computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                        .addComponent(buscaComputadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarComputadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(computadorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, computadorComputadorPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(adicionarComputadorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarComputadorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarComputadorButton))
                    .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                                .addComponent(nomeComputadorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeComputadorTextField))
                            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                                .addComponent(descComputadorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descComputadorTextField))
                            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                                .addComponent(quantidadeComputadorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeComputadorSpinner))
                            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                                .addComponent(idComputadorComputadorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idComputadorComputadorNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limparComputadorButton)))
                        .addContainerGap())))
        );
        computadorComputadorPanelLayout.setVerticalGroup(
            computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscaComputadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarComputadorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(computadorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(computadorComputadorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idComputadorComputadorLabel)
                                    .addComponent(idComputadorComputadorNumberLabel)))
                            .addComponent(limparComputadorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeComputadorLabel)
                            .addComponent(nomeComputadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descComputadorLabel)
                            .addComponent(descComputadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidadeComputadorLabel)
                            .addComponent(quantidadeComputadorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(computadorComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionarComputadorButton)
                            .addComponent(alterarComputadorButton)
                            .addComponent(deletarComputadorButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        componenteComputadorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Componentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter Medium", 0, 14))); // NOI18N

        nomeComponenteTextField.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N

        idComponenteLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        idComponenteLabel.setText("ID Componente:");

        nomeComponenteLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        nomeComponenteLabel.setText("Nome");

        quantidadeComponenteLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        quantidadeComponenteLabel.setText("Quantidade");

        quantidadeComponenteSpinner.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N

        categoriaComponenteLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        categoriaComponenteLabel.setText("Categoria");

        categoriaComponenteComboBox.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        categoriaComponenteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU/Processador", "Cooler CPU", "Placa mãe", "Memoria RAM", "Placa de vídeo", "Armazenamento", "Fonte", "Cabo", "Cooler Gabinete", "Gabinete", "Outro" }));

        adicionarComponenteButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        adicionarComponenteButton.setText("Adicionar");
        adicionarComponenteButton.setEnabled(false);
        adicionarComponenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarComponenteButtonActionPerformed(evt);
            }
        });

        alterarComponenteButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        alterarComponenteButton.setText("Alterar");
        alterarComponenteButton.setEnabled(false);
        alterarComponenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarComponenteButtonActionPerformed(evt);
            }
        });

        deletarComponenteButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        deletarComponenteButton.setText("Deletar");
        deletarComponenteButton.setEnabled(false);
        deletarComponenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarComponenteButtonActionPerformed(evt);
            }
        });

        idComponenteNumberLabel.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        idComponenteNumberLabel.setText("ID");

        componenteComputadorTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        componenteComputadorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Categoria", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        componenteComputadorTable.setFocusable(false);
        componenteComputadorTable.getTableHeader().setReorderingAllowed(false);
        componenteComputadorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                componenteComputadorTableMouseClicked(evt);
            }
        });
        componenteScrollPane.setViewportView(componenteComputadorTable);

        limparComponenteButton.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        limparComponenteButton.setText("Limpar");
        limparComponenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparComponenteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout componenteComputadorPanelLayout = new javax.swing.GroupLayout(componenteComputadorPanel);
        componenteComputadorPanel.setLayout(componenteComputadorPanelLayout);
        componenteComputadorPanelLayout.setHorizontalGroup(
            componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componenteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addComponent(categoriaComponenteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaComponenteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addComponent(quantidadeComponenteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeComponenteSpinner))
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addComponent(nomeComponenteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeComponenteTextField))
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addComponent(idComponenteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idComponenteNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limparComponenteButton))
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adicionarComponenteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarComponenteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarComponenteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        componenteComputadorPanelLayout.setVerticalGroup(
            componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componenteComputadorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idComponenteLabel)
                            .addComponent(idComponenteNumberLabel)))
                    .addComponent(limparComponenteButton))
                .addGap(7, 7, 7)
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeComponenteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeComponenteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaComponenteLabel)
                    .addComponent(categoriaComponenteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeComponenteLabel)
                    .addComponent(quantidadeComponenteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(componenteComputadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarComponenteButton)
                    .addComponent(alterarComponenteButton)
                    .addComponent(deletarComponenteButton))
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(componenteScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componenteComputadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computadorComputadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(computadorComputadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componenteComputadorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computadorComputadorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computadorComputadorTableMouseClicked
        computador.setarCampos();
        
        adicionarComponenteButton.setEnabled(true); 
        alterarComponenteButton.setEnabled(true);
        deletarComponenteButton.setEnabled(true);
    }//GEN-LAST:event_computadorComputadorTableMouseClicked

    private void componenteComputadorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_componenteComputadorTableMouseClicked
        componente.setarCampos();
    }//GEN-LAST:event_componenteComputadorTableMouseClicked

    private void buscarComputadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarComputadorButtonActionPerformed
        computador.atualizar();
    }//GEN-LAST:event_buscarComputadorButtonActionPerformed

    private void limparComputadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparComputadorButtonActionPerformed
        computador.limparCampos();
        
        adicionarComponenteButton.setEnabled(false);
        alterarComponenteButton.setEnabled(false);
        deletarComponenteButton.setEnabled(false);
    }//GEN-LAST:event_limparComputadorButtonActionPerformed

    private void adicionarComputadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarComputadorButtonActionPerformed
        computador.criar();
    }//GEN-LAST:event_adicionarComputadorButtonActionPerformed

    private void alterarComputadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarComputadorButtonActionPerformed
        computador.alterar();
    }//GEN-LAST:event_alterarComputadorButtonActionPerformed

    private void deletarComputadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarComputadorButtonActionPerformed
        computador.deletar();
    }//GEN-LAST:event_deletarComputadorButtonActionPerformed

    private void adicionarComponenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarComponenteButtonActionPerformed
        componente.criar();
    }//GEN-LAST:event_adicionarComponenteButtonActionPerformed

    private void alterarComponenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarComponenteButtonActionPerformed
        componente.alterar();
    }//GEN-LAST:event_alterarComponenteButtonActionPerformed

    private void deletarComponenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarComponenteButtonActionPerformed
        componente.deletar();
    }//GEN-LAST:event_deletarComponenteButtonActionPerformed

    private void limparComponenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparComponenteButtonActionPerformed
        componente.limparCampos();
    }//GEN-LAST:event_limparComponenteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton adicionarComponenteButton;
    private javax.swing.JButton adicionarComputadorButton;
    public static javax.swing.JButton alterarComponenteButton;
    private javax.swing.JButton alterarComputadorButton;
    public static javax.swing.JTextField buscaComputadorTextField;
    private javax.swing.JButton buscarComputadorButton;
    public static javax.swing.JComboBox<String> categoriaComponenteComboBox;
    private javax.swing.JLabel categoriaComponenteLabel;
    private javax.swing.JPanel componenteComputadorPanel;
    public static javax.swing.JTable componenteComputadorTable;
    private javax.swing.JScrollPane componenteScrollPane;
    private javax.swing.JPanel computadorComputadorPanel;
    public static javax.swing.JTable computadorComputadorTable;
    private javax.swing.JScrollPane computadorScrollPane;
    public static javax.swing.JButton deletarComponenteButton;
    private javax.swing.JButton deletarComputadorButton;
    private javax.swing.JLabel descComputadorLabel;
    public static javax.swing.JTextField descComputadorTextField;
    private javax.swing.JLabel idComponenteLabel;
    public static javax.swing.JLabel idComponenteNumberLabel;
    private javax.swing.JLabel idComputadorComputadorLabel;
    public static javax.swing.JLabel idComputadorComputadorNumberLabel;
    private javax.swing.JButton limparComponenteButton;
    private javax.swing.JButton limparComputadorButton;
    private javax.swing.JLabel nomeComponenteLabel;
    public static javax.swing.JTextField nomeComponenteTextField;
    private javax.swing.JLabel nomeComputadorLabel;
    public static javax.swing.JTextField nomeComputadorTextField;
    private javax.swing.JLabel quantidadeComponenteLabel;
    public static javax.swing.JSpinner quantidadeComponenteSpinner;
    private javax.swing.JLabel quantidadeComputadorLabel;
    public static javax.swing.JSpinner quantidadeComputadorSpinner;
    // End of variables declaration//GEN-END:variables
}
